package ipp.estg.cmu_09_8220169_8220307_8220337.viewModels

import android.app.Application
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import ipp.estg.cmu_09_8220169_8220307_8220337.data.room.models.Workout
import ipp.estg.cmu_09_8220169_8220307_8220337.data.retrofit.models.exerciceDbApi.ExerciseItemDataResponse
import ipp.estg.cmu_09_8220169_8220307_8220337.repositories.WorkoutRepository
import ipp.estg.cmu_09_8220169_8220307_8220337.data.retrofit.RemoteApis
import ipp.estg.cmu_09_8220169_8220307_8220337.data.room.LocalDatabase
import kotlinx.coroutines.launch

class WorkoutViewModel(
    application: Application
) : AndroidViewModel(application) {

    private val workoutRepository: WorkoutRepository = WorkoutRepository(
        exerciseDbApi = RemoteApis.getExerciseDbApi(),
        workoutDao = LocalDatabase.getDatabase(application).workoutDao
    )


    var state by mutableStateOf(ScreenState())
        private set

    fun generateWorkout(bodyParts: List<String>) {
        viewModelScope.launch {
            state = state.copy(isGeneratingWorkout = true)

            // load exercises from the repository
            val exercises = workoutRepository.getExercisesByBodyParts(
                bodyParts = bodyParts,
                limit = 10,
                offset = 0
            )

            // store exercises on the state
            state = state.copy(workout = exercises)

            state = state.copy(isGeneratingWorkout = false)
        }
    }

    fun getWorkouts() {
        viewModelScope.launch {
            state = state.copy(isLoading = true)

            val storedWorkouts = workoutRepository.getWorkouts()

            if(storedWorkouts.isNotEmpty()) {
                state = state.copy(storedWorkouts = storedWorkouts)
            }

            state = state.copy(isLoading = false)
        }
    }

    data class ScreenState(
        val isLoading: Boolean = false,
        val isGeneratingWorkout: Boolean = false,
        val error: String? = null,
        val workout: List<ExerciseItemDataResponse> = emptyList(), // exercises generated by the API
        val storedWorkouts: List<Workout> = emptyList() // exercises stored on the local database
    )
}

